"""Build a self-contained Python script for Lightsail that:
1) Has the AFD index inlined (cities/dates/product_ids)
2) Fetches each AFD text from IEM
3) Imports extract_afd_signals from the production module
4) Appends results to /opt/kalshi-weather/research/llm_extractions.jsonl

Outputs the script to research/remote_runner.py
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(ROOT, "research", "afd_index.json")) as f:
    INDEX = json.load(f)

SCRIPT = '''#!/usr/bin/env python3
"""Remote LLM extraction runner. Generated by build_remote_runner.py."""
import json, os, sys, time, urllib.request, urllib.error

INDEX = __INDEX_PLACEHOLDER__

OUT = "/opt/kalshi-weather/research/llm_extractions.jsonl"
os.makedirs(os.path.dirname(OUT), exist_ok=True)
os.environ.setdefault("OLLAMA_MODEL", "llama3.2:1b")
os.environ.setdefault("OLLAMA_TIMEOUT_SECONDS", "120")

# Load already-done keys so reruns resume
done = set()
if os.path.exists(OUT):
    with open(OUT) as f:
        for line in f:
            try:
                r = json.loads(line)
                done.add((r["city"], r["date"]))
            except Exception:
                pass

sys.path.insert(0, "/opt/kalshi-weather/src")
from kalshi_weather.engines.afd_extractor import extract_afd_signals  # noqa: E402

UA = {"User-Agent": "KalshiWeatherTest-research/1.0"}

def fetch_text(product_id):
    parts = product_id.split("-")
    ts, pil = parts[0], parts[3]
    url = f"https://mesonet.agron.iastate.edu/cgi-bin/afos/retrieve.py?pil={pil}&e={ts}"
    for attempt in range(3):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read().decode("utf-8", errors="replace")
        except Exception as e:
            if attempt == 2:
                print(f"fetch fail {product_id}: {e}", flush=True)
                return None
            time.sleep(1.5 * (attempt + 1))

total = len(INDEX)
print(f"start: {total} entries, {len(done)} already done", flush=True)
t0 = time.time()
for i, entry in enumerate(INDEX):
    key = (entry["city"], entry["date"])
    if key in done:
        continue
    text = fetch_text(entry["product_id"])
    if not text:
        rec = {**entry, "extraction_failed": True, "error": "fetch_failed",
               "confidence": None, "model_spread_flag": None,
               "regime": None, "mentioned_today_high_f": None}
    else:
        try:
            r = extract_afd_signals(text)
            rec = {**entry,
                   "confidence": r.confidence,
                   "model_spread_flag": r.model_spread_flag,
                   "regime": r.regime,
                   "mentioned_today_high_f": r.mentioned_today_high_f,
                   "extraction_failed": r.extraction_failed,
                   "raw_llm_response": r.raw_llm_response}
        except Exception as e:
            rec = {**entry, "extraction_failed": True, "error": str(e),
                   "confidence": None, "model_spread_flag": None,
                   "regime": None, "mentioned_today_high_f": None}
    with open(OUT, "a") as f:
        f.write(json.dumps(rec) + "\\n")
    elapsed = time.time() - t0
    print(f"[{i+1}/{total}] {entry['city']} {entry['date']} -> conf={rec.get('confidence')} regime={rec.get('regime')} high={rec.get('mentioned_today_high_f')} fail={rec.get('extraction_failed')} ({elapsed:.0f}s)", flush=True)

print("done", flush=True)
'''

script = SCRIPT.replace("__INDEX_PLACEHOLDER__", json.dumps(INDEX))
out_path = os.path.join(ROOT, "research", "remote_runner.py")
with open(out_path, "w") as f:
    f.write(script)
print(f"wrote {out_path} ({os.path.getsize(out_path)} bytes)")
